[tools]
# runtime
python = ["3.12", "3.9", "3.10", "3.11", "3.13"]
node = "lts"

# compiler
go = "latest"
rust = "latest"
java = "corretto-8"

# python package managers
poetry = "latest"
uv = "latest"

# python dev tools
# ruff = "latest"

# node package managers
pnpm = "latest"

# node dev tools
# biome = "latest"

# task runner
task = "latest"

# cloud vendor clis
aws-cli = "latest"
gcloud = "latest"

# git hooks manager
"pipx:pre-commit" = "4.5.0"  # https://pre-commit.com/
"pipx:lefthook" = "2.0.7"  # https://github.com/evilmartians/lefthook?tab=readme-ov-file#why-lefthook

# not categorized
buf = "latest"
jq = "latest"
bat = "latest"
eza = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
shellcheck = "latest"
bitwarden-secrets-manager = "latest"
"npm:aws-cdk" = "2.1033.0"  # https://docs.aws.amazon.com/cdk/api/v2/docs/aws-construct-library.html
"npm:@anthropic-ai/claude-code" = "2.0.57"  # https://www.claude.com/product/claude-code
"npm:@typespec/compiler" = "1.6.0"  # https://typespec.io/docs/language-basics/visibility/
"pipx:awsume" = "4.5.4"  # https://awsu.me/
"npm:@bitwarden/cli" = "2025.11.0"  # https://bitwarden.com/help/article/cli/
"pipx:typer" = "0.20.0"  # https://typer.tiangolo.com/tutorial/typer-command/#run-with-the-typer-command
"npm:vibe-kanban" = "0.0.126"  # https://www.vibekanban.com/docs
"npm:@google/clasp" = "3.1.3" # https://github.com/google/clasp#readme
"pipx:github/spec-kit" = "v0.0.89"

[tools."http:git-worktree-runner"]  # https://github.com/coderabbitai/git-worktree-runner
version = "2.0.0"
url = "https://github.com/coderabbitai/git-worktree-runner/archive/refs/tags/v{{version}}.tar.gz"
checksum = "sha256:ea5be2610bcd49a7f05806c3cf956d8dd5bc53d51a2f1c2519604586e2b3afa8"
size = 118519

[settings]
idiomatic_version_file_enable_tools = []

# experimental = true
# lockfile = true

[settings.status]
missing_tools = 'always'
show_env = true

[settings.pipx]
uvx = true
