[tools]
# runtime
python = ["3.9", "3.10", "3.11", "3.12", "3.13"]
node = "lts"

# compiler
go = "latest"
rust = "latest"
java = "corretto-8"

# python package managers
poetry = "latest"
uv = "latest"

# node package managers
pnpm = "latest"

# task runner
task = "latest"

# cli
aws-cli = "latest"
buf = "latest"
"npm:aws-cdk" = "2.1033.0"  # https://docs.aws.amazon.com/cdk/api/v2/docs/aws-construct-library.html
"npm:@anthropic-ai/claude-code" = "2.0.46"  # https://www.claude.com/product/claude-code
"npm:@typespec/compiler" = "1.6.0"  # https://typespec.io/docs/language-basics/visibility/
"pipx:pre-commit" = "4.4.0"  # https://pre-commit.com/
"pipx:awsume" = "4.5.4"  # https://awsu.me/
"npm:@bitwarden/cli" = "2025.11.0"  # https://bitwarden.com/help/article/cli/

[tools."http:git-worktree-runner"]  # https://github.com/coderabbitai/git-worktree-runner
version = "1.0.0"
url = "https://github.com/coderabbitai/git-worktree-runner/archive/refs/tags/v1.0.0.tar.gz"
checksum = "sha256:0c3e000fd40654e350ecc5a6453339d9cf42feb75090662379bb2819018ff2f6"
size = 110099

[settings]
idiomatic_version_file_enable_tools = []

# experimental = true
# lockfile = true

[settings.pipx]
uvx = true
