[project]
name = "cli"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.20.0",
    "pydantic>=2.12.5",
]

[project.scripts]
py_cli = "cli:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.8",
]

[tool.pytest.ini_options]
addopts = "--cov=cli --cov-report=term-missing"

[tool.mypy]
python_version = "3.11"
